version: '3.8'
services:
  backend-service:
    build: ./techserv-back
    container_name: tech-serv-back
    restart: always
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}

  frontend-service:
    build: ./tech-serv-front
    container_name: tech-serv-front
    restart: always
    ports:
      - "8085:80"
    depends_on:
      - backend-service